import Head from "next/head";
import Image from "next/image";
import Header from "../../src/Components/Layout/Header";
import SearchContainer from "../../src/Container/Search";

export default function Home({term}) {
  return (
    <div>
      <Head>
        <title>Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <SearchContainer />
    </div>
  );
}

export async function getStaticPaths() {
    return {
      paths: [],
      fallback: true,
    };
  }

  export async function getStaticProps({ params }) {
    return { props: { term : params.term } }
  }