import Head from "next/head";
import Image from "next/image";
import Header from "../src/Components/Layout/Header";
import HomePageCarousel from "../src/Components/Home/Carousel";
import Search from "../src/search";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomePageCarousel />
      <Search />
    </div>
  );
}
